name: Build and deploy infra

on:
  # push:
  #   branches:
  #     - main
  #     - "releases/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Setup AWS SAM to build and deploy infra"
        required: true
        default: "dev"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      - uses: actions/setup-python@v4
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Display dotnet version
        run: dotnet --version
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: sam build
      # - run: sam build -t ./template.yaml --parameter-overrides LambdaArchitecture=x86_64
      #   shell: bash
      # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
